### ISSUE TITLE
why is there a utilities in the root directory and the example notebooks directory?

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/Python-course-materials-for-seismology-students#12]
there should only be one and it should be referenced correctly.

**Comment by seismoChas** [comment]
Because I don't know how to import utilities from the directory above example notebooks... So like the notebooks are in the cartopy directory, but I need to import utilities from two directories up? How do to that?! I guess that needs to be put in the path? I was really just trying to keep things simple in the examples.

**Comment by seismoChas** [comment]
Since none of the notebooks depend on the utilities folder, I removed it from this directory.
